# Generated by Django 2.2.4 on 2019-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
