# Generated by Django 2.2.4 on 2019-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/%Y%m%d/'),
        ),
    ]
