# Generated by Django 2.2.4 on 2019-08-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20190828_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='semester',
            field=models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/%Y-%m-%d/'),
        ),
    ]
